### ISSUE TITLE
MSBuild target assumes correct dotnet is on the path

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/MvcPrecompilation#50]
Currently the MSBuild target assumes that the correct dotnet is on the path [here](https://github.com/aspnet/MvcPrecompilation/blob/rybrande/MsBuildTarget/src/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Design/build/netcoreapp1.1/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Design.targets#L22). This is not a safe assumption in general, as VS uses a different install of dotnet than the commandline and a couple other instances of weirdness.  We should get some more detailed logic in there about finding the correct version.

**Comment by pranavkm** [comment]
An alternative to running the user process is to use a `AssemblyLoadContext` \ `AppDomain` that simulates `dotnet exec` and run precompilation as part of an MSBuild Task. This would remove the dependency on dotnet (while also addressing bitness issues https://github.com/aspnet/MvcPrecompilation/issues/47). @natemcmaster has some code that produces a load context from the deps file. Would be nice to POC this early to verify if this is feasible.

cc @DamianEdwards \ @davidfowl since they were discussing this yesterday.

**Comment by natemcmaster** [comment]
@pranavkm  here is that code. It's ~5 months old an I labeled it "WIP", so not sure how complete/functional it is.

https://github.com/natemcmaster/EntityFramework/blob/6dc4b2b231d5b28472a683e3bdaabc6eba057ccf/src/Tools.DotNet/Internal/DependencyContextExtensions.cs
https://github.com/natemcmaster/EntityFramework/blob/6dc4b2b231d5b28472a683e3bdaabc6eba057ccf/src/Tools.DotNet/Internal/DesignLoadContext.cs

**Comment by pranavkm** [comment]
@natemcmaster mentioned that this approach (as is our current one) doesn't work with ClassLibraries - blocked due to https://github.com/dotnet/cli/issues/2645. Linking it here so we can follow up on the blocking issue.

**Comment by natemcmaster** [comment]
Actually, if you are going to try the AssemblyLoadContext approach, the actual blocking bug is this: https://github.com/dotnet/core-setup/issues/635

**Comment by pranavkm** [comment]
For the 1.1.0-msbuild3 release, there's an `MvcRazorRunCommand` property that can be overriden to specify the full path to `dotnet.exe` if it's not in the path.

```xml
<PropertyGroup>
  <MvcRazorRunCommand Condition="!$(TargetFramework.StartsWith('netcoreapp'))">$(MSBuildThisFileDirectory)..\.dotnet\dotnet.exe</MvRazorRunCommand>
</PropertyGroup>
```

The `Condition` attribute is required only if the application is being multi-targeted.

Similarly, the property can be used to run the precompilation tool using Mono for net451 on a non-Windows OS.
```xml
<PropertyGroup>
  <MvcRazorRunCommand Condition="'$(OS)'!='Windows_NT'">mono $(MvcRazorRunCommand)</MvRazorRunCommand>
</PropertyGroup>
```

**Comment by mikeharder** [comment]
Should this be considered for preview2?  Does this bug mean the CLI zip installer cannot be used with MVC apps?  If so, this seems like a major issue.

**Comment by mikeharder** [comment]
Or add the issue and workaround to a readme or similar docs for Preview2.

**Comment by pranavkm** [comment]
@mikeharder we've had this issue since the 1.0.0 of the tool, so I'm not entirely sure it would warrant requiring a preview2 fix. The msbuild task assumes `dotnet.exe` is in the path, and the workaround has been to either add it to the path or specify it via an MSBuild property `MvcRazorRunCommand`.

**Comment by pranavkm** [comment]
Using MSBuild's muxer if available as part of https://github.com/aspnet/MvcPrecompilation/commit/fe4cc976b9206b218326ed5fb130a331a0c51ae8. We can look running the tool in-proc if we get further issues about this.
