### ISSUE TITLE
Use multiple assemblies with compiled views

### ISSUE THREAD

**Issue by ygoe** [aspnet/MvcPrecompilation#85]
I'm currently investigating how to build an ASP.NET plugin mechanism that allows adding more controllers and views to an existing web application as plugins. I'd probably know how to add routes and have heard about ways to add more controllers to the resolving process. But how can I add more views that can be used by the controllers provided by the plugin? Could I just use this NuGet package for my plugin project and deploy the Plugin.dll and some Plugin.PrecompiledViews.dll and it'll work? (I'm not sure how this web plugin project would look like at all. Maybe just like a full web application project?) Or do I have to register the additional views in the host application somehow? Would that even work? ASP.NET Core seems to magically discover that separate DLL, ILSpy doesn't show any related code in my web application assembly.

**Comment by pranavkm** [comment]
> Could I just use this NuGet package for my plugin project and deploy the Plugin.dll and some Plugin.PrecompiledViews.dll and it'll work?

Yup, that should just work. We do something similar in one of our test applications (https://github.com/aspnet/MvcPrecompilation/tree/dev/testapps/ClassLibraryWithPrecompiledViews) that's then consumed by an application (https://github.com/aspnet/MvcPrecompilation/tree/dev/testapps/ApplicationUsingPrecompiledViewClassLibrary). Simply referencing the package would suffice.

Note that, due to the way we run our tool, your plugin must be application (i.e. targeting `netcoreapp1.x`).

**Comment by pranavkm** [comment]
Closing for now. Feel free to reopen if this is still an open question.
